/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retinoassist;


import java.io.BufferedReader;
import java.io.File;
import java.io.InputStreamReader;
import java.util.ArrayList;
import java.util.List;
import static java.util.stream.DoubleStream.builder;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.filechooser.FileSystemView;
import java.sql.*;

/**
 *
 * @author nikhil
 */
public class PerformExamination extends javax.swing.JFrame {

/**
 * Creates new form PerformExamination
 */
String path;
int id;
int level;
public PerformExamination() {
    initComponents();
    results2.setVisible(false);
    results3.setVisible(false);
    savedata.setVisible(false);
}

public static void saveData(int id, int level){
    try{  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/retinet","nikhil","Nikhil@2001");  
        Statement stmt = con.createStatement();  
        stmt.executeUpdate("UPDATE patient_details SET level = "+level+" WHERE patientId = "+id+";");     
        con.close(); 
        System.out.println("Data saved for patient id = "+id);
    }catch(Exception e){
            System.out.println(e);
    } 
     
}
public int runExamination(){
    int level = 0;
    try{
        System.out.println("Working on - "+System.getProperty("user.dir"));
        String path = "/home/nikhil/NetbeansProjects/RetinoAssist/model/testimages/100_left.jpeg";
        ProcessBuilder builder = new ProcessBuilder("python3",System.getProperty("user.dir")+"/model/model.py",path);
        Process process = builder.start();
        BufferedReader reader = new BufferedReader(new InputStreamReader(process.getInputStream()));
        BufferedReader error = new BufferedReader(new InputStreamReader(process.getErrorStream()));

        String lines;
        level = Integer.parseInt(reader.readLine());
        
        while((lines = error.readLine())!=null){
            System.out.println(lines);
        }

        System.out.println("Detection Completed - Level "+level+" Detected");
    }
    catch(Exception e){
        System.out.print(e);
    }
    return level;
}

/**
 * This method is called from within the constructor to initialize the form.
 * WARNING: Do NOT modify this code. The content of this method is always
 * regenerated by the Form Editor.
 */
@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        image = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        patientid = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        results2 = new javax.swing.JLabel();
        PerformExamination = new javax.swing.JButton();
        results = new javax.swing.JLabel();
        results3 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        savedata = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1300, 800));

        jPanel1.setLayout(null);

        image.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/eyeImage.png"))); // NOI18N
        jPanel1.add(image);
        image.setBounds(100, 120, 500, 500);

        jLabel4.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        jLabel4.setForeground(java.awt.Color.white);
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Perform Examination");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(0, 0, 1300, 42);

        jPanel2.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel2.setText("Patient ID");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(61, 32, 152, 54);

        jLabel3.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jLabel3.setText("File Location");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(61, 104, 152, 50);

        patientid.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel2.add(patientid);
        patientid.setBounds(231, 32, 222, 54);

        jTextField2.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel2.add(jTextField2);
        jTextField2.setBounds(231, 105, 222, 50);

        results2.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        results2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        results2.setText("Proliferative DR");
        jPanel2.add(results2);
        results2.setBounds(40, 370, 440, 42);

        PerformExamination.setText("Perform Examination");
        PerformExamination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PerformExaminationActionPerformed(evt);
            }
        });
        jPanel2.add(PerformExamination);
        PerformExamination.setBounds(60, 200, 392, 57);

        results.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        results.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        results.setText("Results");
        jPanel2.add(results);
        results.setBounds(50, 300, 420, 50);

        results3.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        results3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        results3.setText("Level 5 - Detected");
        jPanel2.add(results3);
        results3.setBounds(40, 420, 440, 42);
        jPanel2.add(jSeparator4);
        jSeparator4.setBounds(40, 300, 440, 40);
        jPanel2.add(jSeparator3);
        jSeparator3.setBounds(40, 350, 440, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(700, 120, 510, 500);

        savedata.setFont(new java.awt.Font("Ubuntu", 0, 36)); // NOI18N
        savedata.setText("Save Data");
        savedata.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savedataActionPerformed(evt);
            }
        });
        jPanel1.add(savedata);
        savedata.setBounds(160, 630, 392, 57);

        jButton7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Help.png"))); // NOI18N
        jButton7.setText("Back");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(160, 710, 390, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/Background2.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PerformExaminationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PerformExaminationActionPerformed
       //Performing Examination
       level = runExamination();
       String[] classes = {"No DR","Mild DR","Moderate DR","Severe DR","Proliferative DR"};
       
       results.setVisible(true);
       if(level == 0)
            results2.setText("Healthy Eye - No DR Detected");
       else
            results2.setText(classes[level]);

       results2.setVisible(true);
       results3.setText("Level "+level+" - Detected");
       results3.setVisible(true);
       savedata.setVisible(true);
    }//GEN-LAST:event_PerformExaminationActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        JFileChooser fc = new JFileChooser();
        int result = fc.showOpenDialog(null);
        if (result == JFileChooser.APPROVE_OPTION) {
            File file = fc.getSelectedFile();
            path = file.getName();
            jTextField2.setText(path);
            image.setIcon(new ImageIcon(file.getAbsolutePath()));
        }
        
    }//GEN-LAST:event_jTextField2MouseClicked

    private void savedataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savedataActionPerformed
        // TODO add your handling code here:
        id = Integer.parseInt(patientid.getText());
       
        saveData(id,level);
    }//GEN-LAST:event_savedataActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        MainPage vp = new MainPage();
        this.setVisible(false);
        vp.setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

/**
 * @param args the command line arguments
 */
public static void main(String args[]) {
    /* Set the Nimbus look and feel */
    //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
    /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
     */
    try {
        for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
            if ("Nimbus".equals(info.getName())) {
                javax.swing.UIManager.setLookAndFeel(info.getClassName());
                break;
            }
        }
    } catch (ClassNotFoundException ex) {
        java.util.logging.Logger.getLogger(PerformExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (InstantiationException ex) {
        java.util.logging.Logger.getLogger(PerformExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (IllegalAccessException ex) {
        java.util.logging.Logger.getLogger(PerformExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    } catch (javax.swing.UnsupportedLookAndFeelException ex) {
        java.util.logging.Logger.getLogger(PerformExamination.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
    }
    //</editor-fold>

    /* Create and display the form */
    java.awt.EventQueue.invokeLater(new Runnable() {
    public void run() {
        new PerformExamination().setVisible(true);
    }
    });
}

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton PerformExamination;
    private javax.swing.JLabel image;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField patientid;
    private javax.swing.JLabel results;
    private javax.swing.JLabel results2;
    private javax.swing.JLabel results3;
    private javax.swing.JButton savedata;
    // End of variables declaration//GEN-END:variables
}
