/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package retinoassist;
import java.sql.*;

/**
 *
 * @author nikhil
 */
public class UserLogin extends javax.swing.JFrame {

    /**
     * Creates new form UserLogin
     */
    public UserLogin() {
        initComponents();
    }

    String username;
    String password;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        usernameLabel = new javax.swing.JTextField();
        passwordLabel = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        loginMsgFeild = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        jPanel1.setLayout(null);

        usernameLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        jPanel1.add(usernameLabel);
        usernameLabel.setBounds(590, 380, 280, 50);

        passwordLabel.setFont(new java.awt.Font("Ubuntu", 0, 18)); // NOI18N
        passwordLabel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordLabelActionPerformed(evt);
            }
        });
        jPanel1.add(passwordLabel);
        passwordLabel.setBounds(590, 440, 280, 50);

        jButton1.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(420, 530, 460, 60);

        loginMsgFeild.setBackground(java.awt.Color.blue);
        loginMsgFeild.setFont(new java.awt.Font("Ubuntu", 0, 24)); // NOI18N
        loginMsgFeild.setForeground(java.awt.Color.white);
        loginMsgFeild.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(loginMsgFeild);
        loginMsgFeild.setBounds(430, 620, 450, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Resources/LoginBackground.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 1300, 800);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1300, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void passwordLabelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordLabelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordLabelActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String username = usernameLabel.getText();
        String password = new String(passwordLabel.getText());
         
        try{  
        Class.forName("com.mysql.cj.jdbc.Driver");  
        Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/retinet","nikhil","Nikhil@2001");   
        Statement stmt = con.createStatement();  
        ResultSet rs = stmt.executeQuery("select * from user_info where username ='"+username+"';");  
        while(rs.next()){
            String password1 = rs.getString("password");
            
            if(password.equals(password1)){
                String username1 =rs.getString("username");
                String name =rs.getString("name");
                String id = rs.getString("id");
                String degree = rs.getString("degree");
                String spcl = rs.getString("spcl");
                String wrd_no = rs.getString("wrd_no");
                String shift = rs.getString("shift");
                String dept = rs.getString("dept");
                String mob = rs.getString("mob");
                String addr = rs.getString("addr");
                String dob = rs.getString("dob");
                MainPage event = new MainPage();
                this.dispose();
                event.setVisible(true);
                event.setNamee(name);
                event.setId(id);
                event.setDegree(degree);
                event.setSpcl(spcl);
                event.setWrd_no(wrd_no);
                event.setShift(shift);
                event.setDept(dept);
                event.setMob(mob);
                event.setAddr(addr);
                event.setDOB(dob);
            }
        }  
          
        con.close();  
        }catch(Exception e){
            //System.out.println(e.getStackTrace());
            System.out.println(e);
        }  

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel loginMsgFeild;
    private javax.swing.JPasswordField passwordLabel;
    private javax.swing.JTextField usernameLabel;
    // End of variables declaration//GEN-END:variables
}
